# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - 6
      - 7
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

archives:
  - formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats: ['zip']

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
